/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registo de conta (F1-VIS-01) */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login (F1-VIS-02) */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar sessão via cookie refresh httpOnly (F1-VIS-02) */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Terminar sessão, revoga refresh token (F1-VIS-02) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar perfil de saúde (F1-CLI-01) */
        get: operations["getMyProfile"];
        /** Criar/atualizar perfil de saúde (F1-CLI-01) */
        put: operations["updateMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pedir geração de plano mensal (F1-CLI-02) */
        post: operations["requestMealPlanGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado/resultado de uma geração (F1-CLI-02) */
        get: operations["getMealPlanGenerationStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Plano ativo completo, payload único (F1-CLI-03) */
        get: operations["getActiveMealPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans/entries/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de uma entrada/receita do plano (F1-CLI-04) */
        get: operations["getMealPlanEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans/entries/{id}/swap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propor/aplicar troca de refeição (F1-CLI-05) */
        post: operations["swapMealPlanEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/meal-plans/entries/{id}/completed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marcar/desmarcar "Comi isto" numa refeição do plano (F1-CLI-04) */
        patch: operations["setMealPlanEntryCompleted"];
        trace?: never;
    };
    "/me/recipes/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Marcar 👍/👎 numa receita (F1-CLI-05) */
        put: operations["setRecipeFeedback"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/shopping-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de compras do plano ativo (F1-CLI-06) */
        get: operations["getMyShoppingList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/shopping-list/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Marcar/desmarcar item (F1-CLI-06) */
        patch: operations["setShoppingListItemChecked"];
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar lojas parceiras ativas (F3-CLI-07) */
        get: operations["listActiveStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/orders": {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar as minhas encomendas, mais recentes primeiro (F3-CLI-07) */
        get: operations["listMyOrders"];
        put?: never;
        /** Encomendar itens da lista de compras a uma loja (F3-CLI-07) */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de uma encomenda (F3-CLI-07) */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cancelar encomenda, só permitido em PENDENTE/ACEITE (F3-CLI-07) */
        patch: operations["cancelOrder"];
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar utilizadores (F2-ADM-01) */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de utilizador (F2-ADM-01) */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/health-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil de saúde do utilizador (ação auditada) (F2-ADM-01) */
        get: operations["getUserHealthProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspender/reativar conta (F2-ADM-01) */
        patch: operations["setUserStatus"];
        trace?: never;
    };
    "/admin/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar lojas (F2-ADM-02) */
        get: operations["listStores"];
        put?: never;
        /** Criar loja (F2-ADM-02) */
        post: operations["createStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stores/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de loja (F2-ADM-02) */
        get: operations["getStore"];
        /** Atualizar loja (F2-ADM-02) */
        put: operations["updateStore"];
        post?: never;
        /** Remover loja, confirmação dupla se houver produtos (F2-ADM-02) */
        delete: operations["deleteStore"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stores/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Suspender/reativar loja (F2-ADM-02) */
        patch: operations["setStoreStatus"];
        trace?: never;
    };
    "/loja/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar produtos da loja (BE-L02/F3-LOJ-01) */
        get: operations["listProducts"];
        put?: never;
        /** Criar produto da loja (BE-L02/F3-LOJ-01) */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loja/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de produto da loja (BE-L02/F3-LOJ-01) */
        get: operations["getProduct"];
        /** Atualizar produto da loja (BE-L02/F3-LOJ-01) */
        put: operations["updateProduct"];
        post?: never;
        /** Remover produto da loja (BE-L02/F3-LOJ-01) */
        delete: operations["deleteProduct"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loja/products/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Ativar/inativar produto da loja (BE-L02/F3-LOJ-01) */
        patch: operations["setProductStatus"];
        trace?: never;
    };
    "/loja/products/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validar ficheiro de import Excel da loja (BE-L03/F3-LOJ-02) */
        post: operations["importProducts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loja/products/import/{jobId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirmar aplicação do import validado da loja (BE-L03/F3-LOJ-02) */
        post: operations["confirmImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loja/products/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Exportar catálogo atual da loja (BE-L03/F3-LOJ-02) */
        get: operations["exportProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/loja/products/import-template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descarregar template de import da loja (BE-L03/F3-LOJ-02) */
        get: operations["getImportTemplate"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar receitas (F2-ADM-05) */
        get: operations["listRecipes"];
        put?: never;
        /** Criar receita (F2-ADM-05) */
        post: operations["createRecipe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de receita (F2-ADM-05) */
        get: operations["getRecipe"];
        /** Atualizar receita (F2-ADM-05) */
        put: operations["updateRecipe"];
        post?: never;
        /** Remover receita (F2-ADM-05) */
        delete: operations["deleteRecipe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recipes/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Publicar/despublicar receita (F2-ADM-05) */
        patch: operations["setRecipeStatus"];
        trace?: never;
    };
    "/admin/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar ingredientes (F2-ADM-05) */
        get: operations["listIngredients"];
        put?: never;
        /** Criar ingrediente (F2-ADM-05) */
        post: operations["createIngredient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalhe de ingrediente (F2-ADM-05) */
        get: operations["getIngredient"];
        /** Atualizar ingrediente (F2-ADM-05) */
        put: operations["updateIngredient"];
        post?: never;
        /** Remover ingrediente, bloqueado se em uso (F2-ADM-05) */
        delete: operations["deleteIngredient"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/metrics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** KPIs, séries e custo IA (F2-ADM-06) */
        get: operations["getMetricsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ErrorCode: "LSA001_VALIDATION" | "LSA002_INVALID_CREDENTIALS" | "LSA003_ACCOUNT_SUSPENDED" | "LSA004_FORBIDDEN" | "LSA005_NOT_FOUND" | "LSA006_DUPLICATE" | "LSA010_PROFILE_INCOMPLETE" | "LSA011_GENERATION_IN_PROGRESS" | "LSA012_GENERATION_LIMIT" | "LSA013_AI_UNAVAILABLE" | "LSA014_NO_ALTERNATIVE" | "LSA015_ADHOC_LIMIT" | "LSA016_STORE_INACTIVE" | "LSA017_ORDER_NOT_CANCELABLE" | "LSA020_IMPORT_INVALID_FILE" | "LSA021_INGREDIENT_IN_USE" | "LSA022_LAST_ADMIN" | "LSA023_RECIPE_INCOMPLETE" | "LSA099_INTERNAL";
        ApiResponseVoid: {
            /** @enum {string} */
            status: "success" | "error";
            code?: components["schemas"]["ErrorCode"];
            message?: string;
            data?: unknown;
        };
        PageResponse: {
            items?: unknown[];
            page?: number;
            size?: number;
            totalItems?: number;
            totalPages?: number;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            confirmPassword: string;
            disclaimerAccepted: boolean;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResult: {
            accessToken?: string;
            user?: {
                /** Format: int64 */
                id?: number;
                name?: string;
                email?: string;
                /** @enum {string} */
                role?: "CLIENTE" | "ADMIN" | "LOJISTA";
                /** @description Só definido quando role === "LOJISTA" — id da loja a que a conta está ligada (FE-L01). */
                storeId?: number | null;
            };
        };
        AuthResponseEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["AuthResult"];
        };
        /** @enum {string} */
        Goal: "PERDER_PESO" | "COMER_MELHOR" | "GANHAR_MASSA" | "GERIR_CONDICAO";
        /** @enum {string} */
        HealthCondition: "NENHUMA" | "DIABETES_TIPO_2" | "HIPERTENSAO" | "DOENCA_CELIACA" | "OUTRA";
        /** @enum {string} */
        BudgetBand: "BAIXO" | "MEDIO" | "CONFORTAVEL";
        Profile: {
            goal?: components["schemas"]["Goal"];
            /** @description FE-Y02 (ago/2026) — 1 ou mais condições (o cliente pode ter, por exemplo, diabetes + hipertensão em simultâneo). Substitui o antigo campo singular `healthCondition`. */
            healthConditions?: components["schemas"]["HealthCondition"][];
            /** @description Texto livre quando `healthConditions` inclui "OUTRA". */
            healthConditionOther?: string;
            allergies?: string[];
            /** @description FE-Y03 (ago/2026) — alimentos excluídos por opção (não por alergia); campo separado de `allergies` a pedido do cliente. */
            foodExclusions?: string[];
            budgetBand?: components["schemas"]["BudgetBand"];
            mealsPerDay?: number;
            /** @description Para quantas pessoas cozinhar/comprar; escala quantidades da lista de compras e das receitas (não kcal/macros). Intervalo 1-8, default 1. */
            householdSize?: number;
            /** @description Vocabulário fechado: vegetariana, vegan, sem_gluten, sem_lactose, alta_proteina, baixo_calorico. Máx. 6 itens. */
            dietaryPreferences?: string[];
        };
        UpdateProfileRequest: components["schemas"]["Profile"];
        ProfileEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Profile"];
        };
        Macros: {
            /** @description percentagem */
            proteina?: number;
            carbs?: number;
            gordura?: number;
            fibra?: number;
        };
        RecipeStep: {
            order?: number;
            text?: string;
        };
        RecipeIngredientLine: {
            /** Format: int64 */
            ingredientId?: number;
            name?: string;
            quantity?: number;
            unit?: string;
        };
        RecipeSnapshot: {
            /** Format: int64 */
            recipeId?: number;
            name?: string;
            kcal?: number;
            prepMinutes?: number;
            estimatedCostMt?: number | null;
            macros?: components["schemas"]["Macros"];
            healthTags?: string[];
            healthNote?: string | null;
            ingredients?: components["schemas"]["RecipeIngredientLine"][];
            steps?: components["schemas"]["RecipeStep"][];
        };
        MealPlanEntry: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            mealSlot?: "PEQUENO_ALMOCO" | "ALMOCO" | "JANTAR" | "LANCHE";
            recipe?: components["schemas"]["RecipeSnapshot"];
            /** @enum {string} */
            feedback?: "NONE" | "LIKE" | "DISLIKE";
            /** @description "Comi isto" — o cliente marcou a refeição como feita. Default false. */
            completed?: boolean;
        };
        MealPlanDay: {
            /** Format: date */
            date?: string;
            weekday?: string;
            totalKcal?: number;
            macros?: components["schemas"]["Macros"];
            entries?: components["schemas"]["MealPlanEntry"][];
        };
        MealPlan: {
            /** Format: int64 */
            id?: number;
            /** Format: date */
            monthStart?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "ARCHIVED";
            days?: components["schemas"]["MealPlanDay"][];
        };
        MealPlanEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["MealPlan"];
        };
        MealPlanEntryEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["MealPlanEntry"];
        };
        SetCompletedRequest: {
            completed: boolean;
        };
        GenerationHandle: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            status?: "GENERATING" | "READY" | "FAILED";
        };
        GenerationHandleEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["GenerationHandle"];
        };
        /** @description "Pedir receita agora" (FE-T) — mini-wizard de receita avulsa fora do plano semanal. */
        AdHocRecipeRequest: {
            /** @enum {string} */
            mealSlot: "PEQUENO_ALMOCO" | "ALMOCO" | "JANTAR" | "LANCHE";
            goal?: components["schemas"]["Goal"];
            /** @description Restrição pontual em texto livre, opcional, máx. 140 caracteres. Guardada no pedido mas não filtra a receita escolhida — o mock não tem IA real para a interpretar. */
            note?: string;
        };
        AdHocRecipeHandle: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            status?: "GENERATING" | "READY" | "FAILED";
            recipe?: components["schemas"]["RecipeSnapshot"] | null;
        };
        AdHocRecipeEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["AdHocRecipeHandle"];
        };
        ReplaceMealPlanEntryRequest: {
            /** Format: int64 */
            recipeId: number;
        };
        MealPlanGenerationEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: {
                /** Format: int64 */
                id?: number;
                /** @enum {string} */
                status?: "GENERATING" | "READY" | "FAILED";
                /** Format: int64 */
                mealPlanId?: number | null;
            };
        };
        FeedbackRequest: {
            /** @enum {string} */
            value: "LIKE" | "DISLIKE" | "NONE";
        };
        SwapAlternative: {
            recipe?: components["schemas"]["RecipeSnapshot"];
        };
        SwapEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: {
                /** @enum {string} */
                state?: "proposed" | "applied";
                alternative?: components["schemas"]["SwapAlternative"];
            };
        };
        ShoppingListItem: {
            /** Format: int64 */
            id?: number;
            ingredientName?: string;
            /** @enum {string} */
            category?: "CEREAIS_E_FARINHAS" | "PROTEINA" | "VEGETAIS_E_FOLHAS" | "LEGUMINOSAS" | "TEMPEROS_E_OLEOS" | "OUTROS";
            quantity?: number;
            unit?: string;
            checked?: boolean;
            estimatedCostMt?: number | null;
            /** Quantidade que o cliente já diz ter, na mesma `unit` do item; default 0 (FE-R01). */
            haveQuantity?: number;
            /** @description Origem do item: `MANUAL` sobrevive a regenerações do plano; `PLANO` é recalculado a cada agregação. @enum {string} */
            origin?: "PLANO" | "MANUAL";
        };
        ShoppingList: {
            /** Format: int64 */
            id?: number;
            totalItems?: number;
            checkedItems?: number;
            estimatedCostMt?: number | null;
            costIsPartial?: boolean;
            items?: components["schemas"]["ShoppingListItem"][];
        };
        ShoppingListEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["ShoppingList"];
        };
        SetCheckedRequest: {
            checked?: boolean;
            /** Quantidade que o cliente já diz ter, na mesma `unit` do item (FE-R01). */
            haveQuantity?: number;
        };
        /** @description Criação de item manual na lista de compras (F1-CLI-06B). */
        CreateShoppingListItemRequest: {
            ingredientName: string;
            category: components["schemas"]["ShoppingListItem"]["category"];
            quantity: number;
            unit: string;
            estimatedCostMt?: number | null;
        };
        ShoppingListItemEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["ShoppingListItem"];
        };
        /** @enum {string} */
        UserStatus: "ACTIVE" | "SUSPENDED";
        User: {
            /** Format: int64 */
            id?: number;
            name?: string;
            email?: string;
            /** @enum {string} */
            role?: "CLIENTE" | "ADMIN" | "LOJISTA";
            status?: components["schemas"]["UserStatus"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
            mealPlanCount?: number;
        };
        UserEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["User"];
        };
        UserPageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["User"][];
            };
        };
        SetStatusRequest: {
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED";
        };
        Store: {
            /** Format: int64 */
            id?: number;
            name?: string;
            city?: string;
            neighborhood?: string | null;
            contact?: string | null;
            /** @enum {string} */
            status?: "ACTIVE" | "SUSPENDED";
            productCount?: number;
        };
        StoreRequest: {
            name: string;
            city: string;
            neighborhood?: string | null;
            contact?: string | null;
        };
        StoreEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Store"];
        };
        StorePageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["Store"][];
            };
        };
        /** @enum {string} */
        OrderStatus: "PENDENTE" | "ACEITE" | "EM_PREPARACAO" | "PRONTA" | "CONCLUIDA" | "RECUSADA" | "CANCELADA";
        /** @description Snapshot de um item da lista de compras no momento da encomenda. */
        OrderItem: {
            ingredientName?: string;
            quantity?: number;
            unit?: string;
            priceMt?: number | null;
        };
        Order: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            storeId?: number;
            storeName?: string;
            storeContact?: string | null;
            // Snapshot do cliente que fez o pedido — mesmo padrão de storeName/storeContact
            // (este mock só tem 1 cliente fixture; sem campo de telefone em lado nenhum do
            // sistema, por isso o "contacto" aqui é o email). Usado pelo Portal da Loja (FE-L04).
            customerName?: string;
            customerContact?: string | null;
            status?: components["schemas"]["OrderStatus"];
            note?: string | null;
            items?: components["schemas"]["OrderItem"][];
            /** Format: date-time */
            createdAt?: string;
        };
        OrderRequest: {
            /** Format: int64 */
            storeId: number;
            note?: string;
            items: {
                /** Format: int64 */
                itemId: number;
                quantity: number;
            }[];
        };
        // FE-L04 · avançar/recusar o estado de uma encomenda do lado da loja — sem endpoint
        // dedicado no contrato original (nasceu só com a perspetiva do cliente, ver OrderRequest).
        OrderStatusUpdateRequest: {
            status: components["schemas"]["OrderStatus"];
            reason?: string | null;
        };
        OrderEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Order"];
        };
        OrderPageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["Order"][];
            };
        };
        Product: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            category?: "CEREAIS" | "PROTEINA" | "VEGETAIS" | "LEGUMINOSAS" | "TEMPEROS" | "OUTROS";
            unitLabel?: string;
            priceMt?: number;
            /** Format: int64 */
            ingredientId?: number | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        ProductRequest: {
            name: string;
            /** @enum {string} */
            category: "CEREAIS" | "PROTEINA" | "VEGETAIS" | "LEGUMINOSAS" | "TEMPEROS" | "OUTROS";
            unitLabel: string;
            priceMt: number;
            /** Format: int64 */
            ingredientId?: number | null;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
        };
        ProductEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Product"];
        };
        ProductPageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["Product"][];
            };
        };
        ImportRowError: {
            row?: number;
            message?: string;
        };
        ImportJob: {
            /** Format: int64 */
            id?: number;
            filename?: string;
            /** @enum {string} */
            status?: "VALIDATED" | "APPLIED" | "DISCARDED" | "FAILED";
            totalRows?: number;
            validRows?: number;
            errorRows?: number;
            createdCount?: number;
            updatedCount?: number;
            errors?: components["schemas"]["ImportRowError"][];
        };
        ImportJobEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["ImportJob"];
        };
        ConfirmImportRequest: {
            /** @default false */
            onlyValidRows: boolean;
        };
        /** @enum {string} */
        RecipeStatus: "DRAFT" | "PUBLISHED";
        Recipe: {
            /** Format: int64 */
            id?: number;
            name?: string;
            description?: string | null;
            prepMinutes?: number;
            servings?: number;
            estimatedCostMt?: number | null;
            healthTags?: string[];
            kcal?: number;
            macros?: components["schemas"]["Macros"];
            status?: components["schemas"]["RecipeStatus"];
            likeCount?: number;
            dislikeCount?: number;
            ingredients?: components["schemas"]["RecipeIngredientLine"][];
            steps?: components["schemas"]["RecipeStep"][];
        };
        RecipeRequest: {
            name: string;
            description?: string | null;
            prepMinutes: number;
            servings: number;
            estimatedCostMt?: number | null;
            healthTags?: string[];
            macrosOverride?: components["schemas"]["Macros"];
            ingredients: components["schemas"]["RecipeIngredientLine"][];
            steps: components["schemas"]["RecipeStep"][];
        };
        RecipeEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Recipe"];
        };
        RecipePageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["Recipe"][];
            };
        };
        SetRecipeStatusRequest: {
            status: components["schemas"]["RecipeStatus"];
        };
        Ingredient: {
            /** Format: int64 */
            id?: number;
            name?: string;
            category?: string;
            baseUnit?: string;
            kcalPer100g?: number;
            proteinPer100g?: number;
            carbsPer100g?: number;
            fatPer100g?: number;
            fiberPer100g?: number;
            referencePriceMt?: number | null;
            active?: boolean;
        };
        IngredientRequest: {
            name: string;
            category: string;
            baseUnit: string;
            kcalPer100g?: number;
            proteinPer100g?: number;
            carbsPer100g?: number;
            fatPer100g?: number;
            fiberPer100g?: number;
            referencePriceMt?: number | null;
            /** @default true */
            active: boolean;
        };
        IngredientEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["Ingredient"];
        };
        IngredientPageEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["PageResponse"] & {
                items?: components["schemas"]["Ingredient"][];
            };
        };
        MetricsSummary: {
            totalUsers?: number;
            newUsersInPeriod?: number;
            mealPlansGenerated?: number;
            aiSuccessRate?: number;
            estimatedAiCostUsd?: number;
            plansPerDay?: {
                /** Format: date */
                date?: string;
                count?: number;
            }[];
            topRecipes?: {
                /** Format: int64 */
                recipeId?: number;
                name?: string;
                likeCount?: number;
                dislikeCount?: number;
            }[];
            bottomRecipes?: {
                /** Format: int64 */
                recipeId?: number;
                name?: string;
                likeCount?: number;
                dislikeCount?: number;
            }[];
            /** FE-X01: pedidos avulsos ("Pedir receita agora") no período — hand-editado, como FE-S01/FE-T01. */
            adHocRecipeRequestsCount?: number;
            /** FE-X02: encomendas agregadas no período — hand-editado, como FE-S01/FE-T01. */
            ordersInPeriod?: {
                total?: number;
                byStatus?: {
                    status?: components["schemas"]["OrderStatus"];
                    count?: number;
                }[];
            };
            /** FE-X03 [Sugestão]: engajamento (streaks) — hand-editado, como FE-S01/FE-T01. */
            engagement?: {
                /** @description Percentagem 0–1 */
                activeStreakPercent?: number;
                avgCompletedDaysInMonth?: number;
            };
        };
        MetricsSummaryEnvelope: components["schemas"]["ApiResponseVoid"] & {
            data?: components["schemas"]["MetricsSummary"];
        };
    };
    responses: {
        /** @description LSA001 — dados inválidos */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA002 — credenciais inválidas */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA003 — conta suspensa */
        Suspended: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA005 — não encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA006 — já existe */
        Duplicate: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA010 perfil incompleto / LSA011 geração em curso */
        GenerationConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA012 — limite diário de gerações atingido */
        GenerationLimit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA014 — sem alternativa disponível */
        NoAlternative: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA016 — loja não está ativa */
        StoreInactive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA017 — encomenda não pode ser cancelada neste estado */
        OrderNotCancelable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA020 — ficheiro de import inválido */
        InvalidFile: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA021 — ingrediente usado em receitas */
        IngredientInUse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA022 — tem de existir pelo menos um administrador ativo */
        LastAdmin: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
        /** @description LSA023 — receita não publicável */
        RecipeIncomplete: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResponseVoid"];
            };
        };
    };
    parameters: {
        PathId: number;
        PageQuery: number;
        SizeQuery: number;
        SortQuery: string;
        SearchQuery: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Conta criada, sessão iniciada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            400: components["responses"]["Validation"];
            409: components["responses"]["Duplicate"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Autenticado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            401: components["responses"]["InvalidCredentials"];
            403: components["responses"]["Suspended"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Novo par de tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseEnvelope"];
                };
            };
            /** @description Refresh inválido/expirado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessão terminada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil (ou 404 se ainda não preenchido) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Perfil gravado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileEnvelope"];
                };
            };
            400: components["responses"]["Validation"];
        };
    };
    requestMealPlanGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Geração aceite, devolve id para polling */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerationHandleEnvelope"];
                };
            };
            409: components["responses"]["GenerationConflict"];
            429: components["responses"]["GenerationLimit"];
        };
    };
    getMealPlanGenerationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado atual da geração */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlanGenerationEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getActiveMealPlan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plano ativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlanEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMealPlanEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entrada com receita snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlanEntryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    swapMealPlanEntry: {
        parameters: {
            query?: {
                /** @description false = propõe alternativa; true = aplica a troca */
                confirm?: boolean;
            };
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Motivo livre e opcional da troca, máx. 140 caracteres. Não filtra a alternativa escolhida — o mock não tem IA real para o interpretar. */
                    reason?: string;
                };
            };
        };
        responses: {
            /** @description Alternativa proposta ou troca aplicada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoAlternative"];
        };
    };
    setMealPlanEntryCompleted: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCompletedRequest"];
            };
        };
        responses: {
            /** @description Estado "Comi isto" atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealPlanEntryEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setRecipeFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Feedback gravado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getMyShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista agregada por categoria */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setShoppingListItemChecked: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCheckedRequest"];
            };
        };
        responses: {
            /** @description Item atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListItemEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listActiveStores: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de lojas ativas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePageEnvelope"];
                };
            };
        };
    };
    listMyOrders: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de encomendas do cliente, mais recentes primeiro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderPageEnvelope"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderRequest"];
            };
        };
        responses: {
            /** @description Encomenda criada, estado inicial PENDENTE */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderEnvelope"];
                };
            };
            400: components["responses"]["Validation"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["StoreInactive"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encomenda */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Encomenda cancelada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["OrderNotCancelable"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de utilizadores */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPageEnvelope"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Utilizador */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getUserHealthProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil de saúde */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusRequest"];
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserEnvelope"];
                };
            };
            409: components["responses"]["LastAdmin"];
        };
    };
    listStores: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de lojas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorePageEnvelope"];
                };
            };
        };
    };
    createStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRequest"];
            };
        };
        responses: {
            /** @description Loja criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreEnvelope"];
                };
            };
            409: components["responses"]["Duplicate"];
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loja */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreEnvelope"];
                };
            };
        };
    };
    updateStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreRequest"];
            };
        };
        responses: {
            /** @description Loja atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreEnvelope"];
                };
            };
        };
    };
    deleteStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Loja removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    setStoreStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatusRequest"];
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreEnvelope"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de produtos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPageEnvelope"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductRequest"];
            };
        };
        responses: {
            /** @description Produto criado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductEnvelope"];
                };
            };
            409: components["responses"]["Duplicate"];
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductEnvelope"];
                };
            };
        };
    };
    updateProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductRequest"];
            };
        };
        responses: {
            /** @description Produto atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductEnvelope"];
                };
            };
        };
    };
    deleteProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    setProductStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "ACTIVE" | "INACTIVE";
                };
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductEnvelope"];
                };
            };
        };
    };
    importProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description Job de import validado, com pré-visualização */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobEnvelope"];
                };
            };
            400: components["responses"]["InvalidFile"];
        };
    };
    confirmImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ConfirmImportRequest"];
            };
        };
        responses: {
            /** @description Import aplicado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportJobEnvelope"];
                };
            };
            /** @description Job já aplicado ou inválido */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ficheiro .xlsx */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    getImportTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ficheiro .xlsx */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": string;
                };
            };
        };
    };
    listRecipes: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de receitas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipePageEnvelope"];
                };
            };
        };
    };
    createRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description Receita criada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeEnvelope"];
                };
            };
        };
    };
    getRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receita */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeEnvelope"];
                };
            };
        };
    };
    updateRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeRequest"];
            };
        };
        responses: {
            /** @description Receita atualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeEnvelope"];
                };
            };
        };
    };
    deleteRecipe: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Receita removida */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    setRecipeStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRecipeStatusRequest"];
            };
        };
        responses: {
            /** @description Estado atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeEnvelope"];
                };
            };
            409: components["responses"]["RecipeIncomplete"];
        };
    };
    listIngredients: {
        parameters: {
            query?: {
                page?: components["parameters"]["PageQuery"];
                size?: components["parameters"]["SizeQuery"];
                sort?: components["parameters"]["SortQuery"];
                q?: components["parameters"]["SearchQuery"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de ingredientes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientPageEnvelope"];
                };
            };
        };
    };
    createIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientRequest"];
            };
        };
        responses: {
            /** @description Ingrediente criado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientEnvelope"];
                };
            };
        };
    };
    getIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingrediente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientEnvelope"];
                };
            };
        };
    };
    updateIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngredientRequest"];
            };
        };
        responses: {
            /** @description Ingrediente atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientEnvelope"];
                };
            };
        };
    };
    deleteIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PathId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingrediente removido */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponseVoid"];
                };
            };
            409: components["responses"]["IngredientInUse"];
        };
    };
    getMetricsSummary: {
        parameters: {
            query?: {
                period?: 7 | 30 | 90;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumo de métricas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsSummaryEnvelope"];
                };
            };
        };
    };
}
