-- DB-06 · Receitas de desenvolvimento — copiadas de RECIPE_CATALOG em
-- levesabor/levesabor-web/src/mocks/fixtures.ts (18 receitas, ids 1-18: 5 pequenos-almoços,
-- 7 almoços, 6 jantares — o total real disponivel no mock, nao os >=40 pedidos no cartao;
-- ver resumo na resposta da tarefa). A receita de teste 9999 ("Bolo de arroz (rascunho)") do
-- mock e propositadamente incompleta para exercitar o erro LSA023_RECIPE_INCOMPLETE e nao e
-- semeada aqui.
--
-- kcal/macros: os valores de RECIPE_CATALOG sao aplicados directamente com
-- macros_override = true, em vez de calculados a partir dos ingredientes por
-- RecipeMacroCalculator — porque a maioria dos ingredientes (V9003) nao tem nutricao real
-- mockada (fica a 0), o que faria o calculo automatico dar macros errados/zerados. Os valores
-- aqui SAO os dados curados reais do mock, tal como a app trata um "override manual do admin".
--
-- meal_tag: derivado da mesma regra que a funcao slotOf() do mock usa (id<=5 pequeno-almoco,
-- id<=12 almoco, resto jantar).
--
-- status: receitas 6, 7, 9, 14 usam o status real de ADMIN_RECIPES no mock (7 fica DRAFT).
-- A receita 2 fica DRAFT porque tem healthTags vazio no mock e RecipePublicationValidator
-- exige >=1 tag de saude para publicar — publica-la aqui seria inconsistente com a regra real
-- da app. As restantes (sem status explicito no mock) ficam PUBLISHED para o catalogo de
-- desenvolvimento nao aparecer vazio ao cliente.
insert into recipes (id, name, description, meal_tag, health_note, prep_minutes, servings, estimated_cost_mt, health_tags, kcal, protein_pct, carbs_pct, fat_pct, fiber_pct, macros_override, status)
overriding system value
values
    (1, 'Papinha de amendoim com banana', null, 'Pequeno-almoço', null, 10, 1, 45, ARRAY['vegetariana','sem_gluten','acucar_controlado'], 320, 12, 58, 24, 6, true, 'PUBLISHED'),
    (2, 'Pão com ovo estrelado e chá de limão', null, 'Pequeno-almoço', null, 12, 1, null, ARRAY[]::text[], 380, 18, 42, 32, 8, true, 'DRAFT'),
    (3, 'Mingau de milho branco com canela', null, 'Pequeno-almoço', null, 15, 1, 35, ARRAY['vegetariana','sem_gluten','acucar_controlado'], 290, 8, 66, 16, 10, true, 'PUBLISHED'),
    (4, 'Omeleta de vegetais com fatia de pão integral', null, 'Pequeno-almoço', 'Baixo em sódio — recomendado para hipertensão, sempre com acompanhamento médico.', 10, 1, 55, ARRAY['baixo_sodio'], 350, 20, 38, 34, 8, true, 'PUBLISHED'),
    (5, 'Xima suave com feijão nhemba (pequeno-almoço reforçado)', null, 'Pequeno-almoço', null, 20, 1, 50, ARRAY['sem_gluten','vegetariana'], 400, 16, 52, 14, 18, true, 'PUBLISHED'),
    (6, 'Xima com matapa e camarão', 'Prato tradicional do sul de Moçambique com camarão e leite de coco.', 'Almoço', null, 40, 1, 180, ARRAY['sem_gluten'], 620, 24, 48, 22, 6, true, 'PUBLISHED'),
    (7, 'Feijão nhemba com arroz e couve', 'Feijão nhemba com arroz e couve, opção vegetariana e económica.', 'Almoço', null, 35, 1, 90, ARRAY['sem_gluten','vegetariana'], 560, 20, 56, 16, 8, true, 'DRAFT'),
    (8, 'Caril de peixe (garoupa) com arroz', null, 'Almoço', null, 45, 1, 220, ARRAY['sem_gluten'], 640, 28, 44, 22, 6, true, 'PUBLISHED'),
    (9, 'Frango à zambeziana com arroz e salada', 'Frango marinado em limão e alho, assado à moda da Zambézia.', 'Almoço', null, 50, 1, 240, ARRAY['sem_gluten'], 700, 30, 42, 22, 6, true, 'PUBLISHED'),
    (10, 'Arroz de coco com feijão jugo', null, 'Almoço', null, 35, 1, 140, ARRAY['sem_gluten','vegetariana'], 610, 16, 60, 18, 6, true, 'PUBLISHED'),
    (11, 'Mandioca cozida com molho de amendoim e folhas', null, 'Almoço', null, 40, 1, 110, ARRAY['sem_gluten','vegetariana'], 580, 14, 58, 22, 6, true, 'PUBLISHED'),
    (12, 'Salada de quiabo com xima e ovo', null, 'Almoço', 'Baixo em sódio — adequado para hipertensão, sempre com acompanhamento médico.', 30, 1, 95, ARRAY['sem_gluten','baixo_sodio'], 480, 18, 52, 20, 10, true, 'PUBLISHED'),
    (13, 'Caril de galinha com batata-doce', null, 'Jantar', null, 45, 1, 200, ARRAY['sem_gluten'], 560, 26, 46, 22, 6, true, 'PUBLISHED'),
    (14, 'Peixe grelhado com legumes salteados', 'Peixe grelhado simples com legumes salteados, baixo em sódio.', 'Jantar', 'Baixo em sódio — recomendado para hipertensão, sempre com acompanhamento médico.', 30, 1, 210, ARRAY['sem_gluten','baixo_sodio'], 500, 32, 34, 24, 10, true, 'PUBLISHED'),
    (15, 'Feijão jugo com arroz e tomate', null, 'Jantar', null, 35, 1, 100, ARRAY['sem_gluten','vegetariana'], 540, 18, 58, 16, 8, true, 'PUBLISHED'),
    (16, 'Matapa com xima (jantar leve)', null, 'Jantar', null, 35, 1, 130, ARRAY['sem_gluten'], 470, 16, 48, 26, 10, true, 'PUBLISHED'),
    (17, 'Sopa de mandioca com legumes e frango desfiado', null, 'Jantar', 'Baixo em sódio — recomendado para hipertensão, sempre com acompanhamento médico.', 40, 1, 120, ARRAY['sem_gluten','baixo_sodio'], 430, 22, 50, 16, 12, true, 'PUBLISHED'),
    (18, 'Frango grelhado com salada de repolho', null, 'Jantar', null, 30, 1, 190, ARRAY['sem_gluten'], 480, 34, 32, 24, 10, true, 'PUBLISHED');

select setval(pg_get_serial_sequence('recipes', 'id'), (select max(id) from recipes));

insert into recipe_ingredients (recipe_id, ingredient_id, name_snapshot, quantity, unit) values
    (1, 1, 'Amendoim moído', 40, 'g'),
    (1, 2, 'Banana', 1, 'unidade'),
    (1, 3, 'Água', 200, 'ml'),
    (2, 4, 'Pão', 1, 'unidade'),
    (2, 5, 'Ovo', 1, 'unidade'),
    (2, 6, 'Óleo de cozinha', 5, 'ml'),
    (2, 7, 'Chá (folhas ou saqueta)', 1, 'saqueta'),
    (2, 8, 'Limão', 0.5, 'unidade'),
    (3, 9, 'Farinha de milho (fuba)', 60, 'g'),
    (3, 3, 'Água', 300, 'ml'),
    (3, 10, 'Canela em pau', 1, 'unidade'),
    (4, 5, 'Ovo', 2, 'unidade'),
    (4, 11, 'Tomate', 50, 'g'),
    (4, 12, 'Cebola', 30, 'g'),
    (4, 13, 'Pão integral', 1, 'fatia'),
    (4, 6, 'Óleo de cozinha', 5, 'ml'),
    (5, 9, 'Farinha de milho (fuba)', 80, 'g'),
    (5, 14, 'Feijão nhemba cozido', 100, 'g'),
    (5, 3, 'Água', 200, 'ml'),
    (6, 9, 'Farinha de milho (fuba)', 120, 'g'),
    (6, 15, 'Folhas de mandioca (matapa)', 150, 'g'),
    (6, 16, 'Camarão', 100, 'g'),
    (6, 17, 'Leite de coco', 100, 'ml'),
    (6, 18, 'Alho', 5, 'g'),
    (7, 14, 'Feijão nhemba', 120, 'g'),
    (7, 19, 'Arroz', 100, 'g'),
    (7, 20, 'Couve', 80, 'g'),
    (7, 12, 'Cebola', 30, 'g'),
    (8, 21, 'Peixe (garoupa)', 150, 'g'),
    (8, 19, 'Arroz', 100, 'g'),
    (8, 17, 'Leite de coco', 80, 'ml'),
    (8, 11, 'Tomate', 60, 'g'),
    (8, 22, 'Piripiri', 2, 'g'),
    (9, 23, 'Frango', 200, 'g'),
    (9, 17, 'Leite de coco', 60, 'ml'),
    (9, 8, 'Limão', 1, 'unidade'),
    (9, 18, 'Alho', 8, 'g'),
    (9, 19, 'Arroz', 100, 'g'),
    (10, 19, 'Arroz', 120, 'g'),
    (10, 17, 'Leite de coco', 100, 'ml'),
    (10, 24, 'Feijão jugo', 100, 'g'),
    (11, 25, 'Mandioca', 250, 'g'),
    (11, 1, 'Amendoim moído', 40, 'g'),
    (11, 15, 'Folhas de mandioca (matapa)', 100, 'g'),
    (12, 26, 'Quiabo', 150, 'g'),
    (12, 9, 'Farinha de milho (fuba)', 80, 'g'),
    (12, 5, 'Ovo', 1, 'unidade'),
    (12, 11, 'Tomate', 40, 'g'),
    (13, 23, 'Frango', 180, 'g'),
    (13, 27, 'Batata-doce', 150, 'g'),
    (13, 17, 'Leite de coco', 80, 'ml'),
    (13, 12, 'Cebola', 30, 'g'),
    (14, 21, 'Peixe (garoupa)', 180, 'g'),
    (14, 20, 'Couve', 80, 'g'),
    (14, 11, 'Tomate', 50, 'g'),
    (14, 8, 'Limão', 0.5, 'unidade'),
    (15, 24, 'Feijão jugo', 120, 'g'),
    (15, 19, 'Arroz', 90, 'g'),
    (15, 11, 'Tomate', 60, 'g'),
    (16, 15, 'Folhas de mandioca (matapa)', 150, 'g'),
    (16, 17, 'Leite de coco', 80, 'ml'),
    (16, 9, 'Farinha de milho (fuba)', 70, 'g'),
    (16, 1, 'Amendoim moído', 20, 'g'),
    (17, 25, 'Mandioca', 150, 'g'),
    (17, 23, 'Frango', 100, 'g'),
    (17, 12, 'Cebola', 30, 'g'),
    (17, 20, 'Couve', 50, 'g'),
    (18, 23, 'Frango', 180, 'g'),
    (18, 28, 'Repolho', 100, 'g'),
    (18, 11, 'Tomate', 40, 'g'),
    (18, 8, 'Limão', 0.5, 'unidade');

insert into recipe_steps (recipe_id, step_order, text) values
    (1, 1, 'Tosta o amendoim moído numa panela seca por 2 minutos.'),
    (1, 2, 'Junta a água aos poucos, mexendo até engrossar.'),
    (1, 3, 'Corta a banana em rodelas e serve por cima.'),
    (2, 1, 'Aquece o óleo numa frigideira e estrela o ovo.'),
    (2, 2, 'Corta o pão ao meio e coloca o ovo lá dentro.'),
    (2, 3, 'Ferve água para o chá e espreme o limão antes de servir.'),
    (3, 1, 'Dissolve a fuba num pouco de água fria.'),
    (3, 2, 'Leva o resto da água a ferver com a canela.'),
    (3, 3, 'Junta a mistura de fuba, mexendo sempre até engrossar.'),
    (4, 1, 'Bate os ovos e tempera sem sal, apenas ervas.'),
    (4, 2, 'Refoga o tomate e a cebola em pouco óleo.'),
    (4, 3, 'Junta os ovos batidos e deixa cozinhar em lume brando.'),
    (4, 4, 'Serve com a fatia de pão integral.'),
    (5, 1, 'Prepara a xima cozendo a fuba com água até ficar consistente.'),
    (5, 2, 'Aquece o feijão nhemba já cozido.'),
    (5, 3, 'Serve a xima com o feijão por cima.'),
    (6, 1, 'Cozinha as folhas de matapa trituradas em lume brando.'),
    (6, 2, 'Junta o leite de coco, o alho e o camarão, deixa apurar 15 minutos.'),
    (6, 3, 'Prepara a xima à parte com a fuba e água.'),
    (6, 4, 'Serve a xima acompanhada da matapa.'),
    (7, 1, 'Coze o feijão nhemba até ficar macio.'),
    (7, 2, 'Coze o arroz em água com uma pitada de sal.'),
    (7, 3, 'Refoga a couve com a cebola.'),
    (7, 4, 'Serve os três juntos no prato.'),
    (8, 1, 'Tempera o peixe e deixa marinar 10 minutos.'),
    (8, 2, 'Refoga o tomate, junta o leite de coco e o piripiri.'),
    (8, 3, 'Adiciona o peixe e deixa cozinhar em lume brando 15 minutos.'),
    (8, 4, 'Serve com arroz branco.'),
    (9, 1, 'Marina o frango com limão e alho por 30 minutos.'),
    (9, 2, 'Grelha o frango, pincelando com leite de coco.'),
    (9, 3, 'Serve com arroz branco e salada fresca.'),
    (10, 1, 'Coze o feijão jugo até amaciar.'),
    (10, 2, 'Cozinha o arroz com leite de coco em vez de água.'),
    (10, 3, 'Mistura o feijão jugo ao arroz antes de servir.'),
    (11, 1, 'Coze a mandioca até ficar macia.'),
    (11, 2, 'Prepara o molho de amendoim com um pouco de água.'),
    (11, 3, 'Refoga as folhas e junta ao molho.'),
    (11, 4, 'Serve a mandioca com o molho por cima.'),
    (12, 1, 'Coze o quiabo em água sem sal.'),
    (12, 2, 'Prepara a xima à parte.'),
    (12, 3, 'Cozinha o ovo e corta o tomate em cubos.'),
    (12, 4, 'Monta o prato com xima, quiabo, ovo e tomate.'),
    (13, 1, 'Refoga a cebola e junta o frango em pedaços.'),
    (13, 2, 'Adiciona o leite de coco e deixa apurar.'),
    (13, 3, 'Junta a batata-doce cozida e serve quente.'),
    (14, 1, 'Tempera o peixe apenas com limão e ervas.'),
    (14, 2, 'Grelha o peixe dos dois lados.'),
    (14, 3, 'Salteia a couve e o tomate em pouco óleo.'),
    (14, 4, 'Serve o peixe com os legumes salteados.'),
    (15, 1, 'Coze o feijão jugo até ficar macio.'),
    (15, 2, 'Cozinha o arroz em água com uma pitada de sal.'),
    (15, 3, 'Refoga o tomate e junta ao feijão.'),
    (15, 4, 'Serve o feijão sobre o arroz.'),
    (16, 1, 'Cozinha as folhas de matapa trituradas com o leite de coco.'),
    (16, 2, 'Junta o amendoim moído e deixa apurar.'),
    (16, 3, 'Prepara a xima à parte e serve com a matapa.'),
    (17, 1, 'Coze o frango e desfia-o.'),
    (17, 2, 'Coze a mandioca e a cebola até amaciarem.'),
    (17, 3, 'Junta a couve e o frango desfiado, deixa apurar 5 minutos.'),
    (18, 1, 'Tempera o frango com limão e grelha até dourar.'),
    (18, 2, 'Corta o repolho e o tomate em tiras finas.'),
    (18, 3, 'Tempera a salada com um fio de azeite e serve com o frango.');
